# Single-node Teleport cluster called "one" (runs all 3 roles: proxy, auth and node)
teleport:
  nodename: one
  log:
    output: /var/lib/teleport/teleport.log
    severity: INFO

  data_dir: /root/go/src/github.com/gravitational/teleport/docker/data/one
  storage:
      path: /root/go/src/github.com/gravitational/teleport/docker/data/one/backend
      type: dir

auth_service:
  enabled: yes

  authentication:
    type: local
    second_factor: off

  cluster_name: one
  tokens: 
       - "node,auth,proxy:foo"
       - "trustedcluster:bar"

ssh_service:
  enabled: yes
  labels:
      cluster: one
  commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m

proxy_service:
  enabled: yes
